let productData = [
    {
        id: 1,
        name: "Quilted giled with hood",
        img: "assets/images/shirt1.webp",
        rating: 2.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        size:['xs', 's', 'm'],
        price: 145, 
        feature: true,
    },
    {
        id: 2,
        name: "Quilted giled with hood",
        img: "assets/images/pant1.webp",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        size:['xs', 's', 'm'],
        price: 145,
        feature: true,
    },
    {
        id: 3,
        name: "Quilted giled with hood",
        img: "assets/images/productimg.png",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        size:['xs', 's', 'm'],
        price: 145,
        feature: true,
    },
    {
        id: 4,
        name: "Quilted giled with hood",
        img: "assets/images/productimg.png",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        size:['xs', 's', 'm'],
        price: 145,
        feature: true,
    },
    {
        id: 5,
        name: "Quilted giled with hood",
        img: "assets/images/productimg.png",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        size:['xs', 's', 'm'],
        price: 145,
        feature: false,
    },
    {
        id: 6,
        name: "Quilted giled with hood",
        img: "assets/images/productimg.png",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        size:['xs', 's', 'm'],
        price: 145,
        feature: false,
    },
    {
        id: 7,
        name: "Quilted giled with hood",
        img: "assets/images/productimg.png",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        size:['xs', 's', 'm'],
        price: 145,
        feature: false,
    },
    {
        id: 8,
        name: "Quilted giled with hood",
        img: "assets/images/productimg.png",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        size:['xs', 's', 'm'],
        price: 145,
        feature: false,
    },
]
module.exports = productData;